### ISSUE TITLE
Calendar: event edit panel cuts off

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1094]
### Description
Calendar: event edit panel cuts off -- can't display the whole thing even when scrolling sideways 

### Steps to reproduce
1. Open Calendar on mobile
2. Click an event and attempt to edit it
3. Attempt to interact with edit panel (including attempting to scroll in order to view parts of the panel which are cut off)

![Image](https://github.com/cryptpad/cryptpad/assets/34193395/80b252ad-2da3-4997-a1a2-68552488f372)

### Expected behavior
Event edit panel should be either entirely visible in the frame, or easily visible when scrolling across the screen

### Extensions
n/a

### Version
5.3.0

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/da8304a5-7298-45ee-920a-a0ff9b1d1b52)

**Comment by davidbenque** [comment]
We should try to make this dialog fully responsive. Might be hard because of TUI styles we have to override

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/b027a925-def0-4cb0-858e-e5f2a6c5f8d4)

**Comment by davidbenque** [comment]
I would rather not rely on reducing the font-size for small screens to make the reminders fit. Seems like there should be a more robust solution

**Comment by davidbenque** [comment]
![Screen Shot 2023-09-27 at 10 40 17](https://github.com/cryptpad/cryptpad/assets/11028490/47a16d12-824a-448d-867d-e17eb510f707)

There are still some issues with this solution
- start and end fields are different than on big screens (should investigate reason)
- the layout of reminders is broken because we currently rely on a fixed width (which is not an ideal solution either)

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/0ff0196d-2f1c-4166-a54c-ca9198e913e6)
