### ISSUE TITLE
bower deprecation warning

### ISSUE THREAD

**Issue by anadahz** [cryptpad/cryptpad#295]
While building cryptpad I get the following deprecation warning:
```
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects.
Please consider Yarn and Webpack or Parcel.
You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

**Comment by ansuz** [comment]
We will very likely move to one of these other package managers at some point in the future, but it seems like it's a safe tool for now.

**Comment by zimbatm** [comment]
The bower dependency makes it quite difficult to package the project for me. Because bower is deprecated the tooling to generate nix code from the bower.json is not very well maintained. bower2nix is quite slow and the output needs to be tweaked after the fact as well.

Not sure if this is a motivation for you but it would make my life much easier :)

**Comment by ansuz** [comment]
I much prefer npm to bower. I'm using it in combination with browserify for my personal projects.

The main things stopping us is that moving from bower to npm will take a significant amount of time and that for most users it won't improve their experience of using CryptPad. We've also discussed moving away from requirejs and implementing a build system, which _would_ directly contribute to visible improvements, but this is an even bigger job.

We're waiting to hear back about some funding which would directly finance this work, but until we know more I can't promise to fit it into our roadmap.

**Comment by zimbatm** [comment]
Thanks I appreciate that it's not a priority.

For reference https://github.com/NixOS/nixpkgs/pull/61513 is adding cryptpad to nixpkgs. Right now there is too much manual patching to automate the upgrade process so the package will likely be stuck at that version until bower gets removed.

**Comment by ansuz** [comment]
2.21.0 isn't the worst version to get stuck at, I suppose.

If that funding comes through then we should be able to drop bower by Autumn 2019, hopefully we'll be able to resume the NixOS packaging then.

**Comment by blitz** [comment]
@ansuz Do you have any news? I'd love to automate the update process for the NixOS package and the bower dependency still prevents this.

**Comment by Pamplemousse** [comment]
Hi there, bumping this thread again:

Although Bower is still maintained on paper, its developpers recommend not to use it for new project (see https://bower.io/).
It means less and less projects are relying on it, and tooling around it is becoming obsolete, thus unmaintained.
For example, the [nix](https://nixos.org/) ecosystem used to rely on [`bower2nix`](https://github.com/rvl/bower2nix) to package bower components, but it hasn't been updated in the last 4 years, and has several blocking issues by now...

As a consequence, we are unable to upgrade `cryptpad` to its latest version for nix users: NixOS/nixpkgs#128154 .

cc @zimbatm @blitz , and @ansuz

**Comment by martinetd** [comment]
It's been a year since the last bump, also coming from nixos here... :)
The nixos package is stuck on an old version with node 12, which is EOL and unsafe. I'm trying to upgrade it but not getting much success at the moment, there's work in progress on bower2nix in https://github.com/rvl/bower2nix/pull/22 and an updated fork at https://git.deuxfleurs.fr/Deuxfleurs/nixcfg/src/branch/main/app/cryptpad/build/default.nix I need to spend some more time on this...

Have you gotten any luck securing funding for this? #881 (bundling js for better perf) might be a good lever for this as I believe it could make a decent difference in loading times and justify finally moving away from bower.

**Comment by mthld** [comment]
Hello, thanks for your interest in CryptPad!

Even if I can't announce any ETA, migrating away from Bower is in our roadmap. Thank you for your patience. :)

**Comment by Pamplemousse** [comment]
`cryptpad` has been removed from `nixpkgs` because it was unmaintained, because tooling around `bower` was.
I am saddened to have to decommission my `cryptpad` instance...

I can't see anything explicitly related to moving away from `bower` in https://cryptpad.fr/kanban/#/2/kanban/view/PLM0C3tFWvYhd+EPzXrbT+NxB76Z5DtZhAA5W5hG9wo/ .

**Comment by davidbenque** [comment]
We have now removed Bower. Thanks @Pamplemousse for the help resolving this. I hope this will improve CryptPad compatibility with NixOS

**Comment by martinetd** [comment]
Thank you both !!

Sorry for piggy-backing the issue -- @Pampemousse will you be reintroducing the package to nixpkgs, or shall I have a look next week-ish?

**Comment by Pamplemousse** [comment]
@martinetd This is not my priority at the moment, so please go for it if you can. Feel free to cc me in any PR you make to `nixpkgs` :slightly_smiling_face:
